## Setting the environment for Colab

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd "/content/drive/My Drive/Colab Notebooks/w266_final/project_re"

/content/drive/.shortcut-targets-by-id/1I3W7Z7rz_YfsjBjX7z4zTzGbr-iKTrmD/w266_final/project_re


In [3]:
#pip installations for colab
!pip install transformers
!pip install pytorch_pretrained_bert

     |████████████████████████████████| 1.3MB 6.0MB/s 
     |████████████████████████████████| 890kB 39.4MB/s 
     |████████████████████████████████| 2.9MB 43.2MB/s 
     |████████████████████████████████| 1.1MB 43.6MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=550e156aa258ab2e3fa94ad2bc6200db7d19f737d10874ca4bc67feafe197854
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses
     |████████████████████████████████| 133kB 5.2MB/s 
     |████████████████████████████████| 133kB 24.3MB/s 
     |████████████████████████████████| 6.9MB 34.5MB/s 
     |████████████████████████████████| 71kB 8.1MB/s 
ERROR: botocore 1.19.23 has requirement urllib3<1.27,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.24.3 which is incompatible.


In [5]:
%load_ext autoreload
#%autoreload
import os, json
from types import SimpleNamespace
from experiment import run_model
from eval import calculate_stats
import pickle
from datetime import datetime 
import torch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# device = "cpu"

In [7]:
config_folder = "config/"

class obj(object):
    def __init__(self, d):
        for a, b in d.items():
            if isinstance(b, (list, tuple)):
               setattr(self, a, [obj(x) if isinstance(x, dict) else x for x in b])
            else:
               setattr(self, a, obj(b) if isinstance(b, dict) else b)

with open(os.path.join(config_folder, "config.json")) as f:
    config = obj(json.load(f))

In [8]:
train_inputs, train_labels, train_preds, train_loss, dev_inputs, dev_labels, dev_loss, dev_preds = run_model(config, device)

INFO:root:***** Running training *****
INFO:root:  Num examples = 61014
INFO:root:  Batch size = 12
INFO:root:  Num steps = 25420


from model {'config': <model.model_config.config object at 0x7f9899b8d588>, 'bert_features': 768, 'layer1_features': 256, 'label_classes': 9, 'kernel_1': 8, 'kernel_2': 10, 'kernel_3': 12, 'out_size': 768, 'stride': 2} in feature 427776


INFO:filelock:Lock 140293390782816 acquired on /root/.cache/torch/transformers/b21d5a31a72925e995ffe402c1fc581bbcd2edeccfdfc99c644db9c8993b69c3.8a57b13360e7becd2face5c0f1f453e918ee57ca9cac6babc6a3081963efecbf.lock


INFO:filelock:Lock 140293390782816 released on /root/.cache/torch/transformers/b21d5a31a72925e995ffe402c1fc581bbcd2edeccfdfc99c644db9c8993b69c3.8a57b13360e7becd2face5c0f1f453e918ee57ca9cac6babc6a3081963efecbf.lock
INFO:filelock:Lock 140293390038352 acquired on /root/.cache/torch/transformers/bb92901d75bb47e4613bb4674299260f5771cccd3139fbeeaf2b3e29dae0ce57.2961ba715ddc7fc9de233b7f88e7cd685d828debe7fe8a96aed60b6b75358584.lock


INFO:filelock:Lock 140293390038352 released on /root/.cache/torch/transformers/bb92901d75bb47e4613bb4674299260f5771cccd3139fbeeaf2b3e29dae0ce57.2961ba715ddc7fc9de233b7f88e7cd685d828debe7fe8a96aed60b6b75358584.lock


Epoch:   0%|          | 0/5 [00:00<?, ?it/s]

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Epoch:  20%|██        | 1/5 [31:10<2:04:41, 1870.33s/it]


so far epoch accuracy:  0.9083652932113941


Epoch:  40%|████      | 2/5 [1:02:22<1:33:32, 1870.81s/it]


so far epoch accuracy:  0.969990493984987


Epoch:  60%|██████    | 3/5 [1:33:38<1:02:24, 1872.31s/it]


so far epoch accuracy:  0.9729898056183827


Epoch:  80%|████████  | 4/5 [2:04:53<31:13, 1873.31s/it]  


so far epoch accuracy:  0.9748910086209722


Epoch: 100%|██████████| 5/5 [2:36:02<00:00, 1872.40s/it]


so far epoch accuracy:  0.9757760513980398
Training complete
Best val Acc: 0.975776


INFO:root:***** Running training *****
INFO:root:  Num examples = 15304
INFO:root:  Batch size = 12
INFO:root:  Num steps = 6375


In [ ]:
train_inputs, train_labels, train_preds, train_loss, dev_inputs, dev_labels, dev_loss, dev_preds

(array([[  101,   152,  2064, ...,     0,     0,     0],
        [  101,   107,  2508, ...,     0,     0,     0],
        [  101,   124,   114, ...,     0,     0,     0],
        ...,
        [  101, 10999,  1108, ...,     0,     0,     0],
        [  101,   164,   115, ...,     0,     0,     0],
        [  101,   164,   115, ...,     0,     0,     0]]),
 array([1, 2, 0, ..., 8, 0, 8]),
 array([1, 2, 0, ..., 8, 0, 8]),
 1.4094005156876181,
 array([[  101, 20452, 19934, ...,     0,     0,     0],
        [  101,  1192,  1127, ...,     0,     0,     0],
        [  101,  1556, 15970, ...,     0,     0,     0],
        ...,
        [  101,  1192,  1431, ...,     0,     0,     0],
        [  101,   160,  2346, ...,     0,     0,     0],
        [  101,  1109,  1286, ...,     0,     0,     0]]),
 array([8, 3, 8, ..., 8, 8, 8]),
 1.4126754786153572,
 array([8, 3, 8, ..., 8, 8, 8]))

In [ ]:
import numpy as np
np.array(dev_labels).shape, np.array(dev_preds).shape, np.array(train_preds).shape, np.array(train_labels).shape

((15304,), (15304,), (61014,), (61014,))

In [ ]:
%autoreload
train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_labels,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(dev_labels,dev_preds )


 label: [1 2 0 ... 8 0 8]

 preds: [1 2 0 ... 8 0 8]

 label: [8 3 8 ... 8 8 8]

 preds: [8 3 8 ... 8 8 8]


In [ ]:
all_experiment_results = []
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score, 
                               dev_labels, dev_preds,train_labels,train_preds, train_inputs, dev_inputs])
len(all_experiment_results[0])

13

In [ ]:
dev_label_matches_df

predicted
labels         matched           
ADE-Drug       False          250
Dosage-Drug    False           25
               True           908
Duration-Drug  False           10
               True           126
Form-Drug      False           32
               True           922
Frequency-Drug False           19
               True          1250
Reason-Drug    False            8
               True          1026
Route-Drug     False           46
               True          1099
Strength-Drug  False           22
               True          1360
no relation    False            2
               True          8199

In [ ]:
all_model_results_pickle_file = config.programsettings.REPORTS_DIR + "multi_model_experiment_results_" + str(datetime.now()).replace(":", "_").replace(".", "_") + ".pkl"
with open(all_model_results_pickle_file, "wb") as f:
    pickle.dump(all_experiment_results, f)

In [ ]:
all_model_results_pickle_file = "reports/re/multi_model_experiment_results_5epochs_256_2fc_weighted.pkl"
with open(all_model_results_pickle_file, "rb") as f:
    all_results = pickle.load(f)

In [ ]:
all_results

[['<__main__.obj object at 0x7f19844f7cf8>',
  1.4094005156876181,
  1.4126754786153572,
  0.9633676617185613,
  0.8596023186182715,
  0.9604878523132441,
  0.8547828221290632,
  array([8, 3, 8, ..., 8, 8, 8]),
  array([8, 3, 8, ..., 8, 8, 8]),
  array([1, 2, 0, ..., 8, 0, 8]),
  array([1, 2, 0, ..., 8, 0, 8]),
  array([[  101,   152,  2064, ...,     0,     0,     0],
         [  101,   107,  2508, ...,     0,     0,     0],
         [  101,   124,   114, ...,     0,     0,     0],
         ...,
         [  101, 10999,  1108, ...,     0,     0,     0],
         [  101,   164,   115, ...,     0,     0,     0],
         [  101,   164,   115, ...,     0,     0,     0]]),
  array([[  101, 20452, 19934, ...,     0,     0,     0],
         [  101,  1192,  1127, ...,     0,     0,     0],
         [  101,  1556, 15970, ...,     0,     0,     0],
         ...,
         [  101,  1192,  1431, ...,     0,     0,     0],
         [  101,   160,  2346, ...,     0,     0,     0],
         [  101,  1

In [ ]:
dev_labels = all_results[0][7]
dev_preds = all_results[0][8]

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(dev_labels,dev_preds ))

              precision    recall  f1-score   support

           0       0.81      0.99      0.89      1034
           1       0.99      0.96      0.97      1145
           2       0.97      0.98      0.98      1382
           3       0.99      0.99      0.99      1269
           4       0.94      0.93      0.93       136
           5       0.95      0.97      0.96       954
           6       0.97      0.97      0.97       933
           7       0.00      0.00      0.00       250
           8       1.00      1.00      1.00      8201

    accuracy                           0.97     15304
   macro avg       0.85      0.87      0.85     15304
weighted avg       0.96      0.97      0.97     15304



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Analyzing results

In [ ]:
with open("reports/re/multi_model_experiment_results_2020-11-19 20_25_02_351087.pkl", "rb") as f:
  all_model_results_pickle_file = pickle.load(f)

In [ ]:
all_model_results_pickle_file

[['<__main__.obj object at 0x7f098018dac8>',
  0.012548324644060544,
  0.047653015470251976,
  0.9938410610583791,
  0.9921212179856703,
  0.9823099468862545,
  0.9710182287919125,
  array([6, 8, 8, ..., 5, 8, 1]),
  array([6, 8, 8, ..., 5, 8, 1]),
  array([8, 8, 8, ..., 2, 8, 0]),
  array([8, 8, 8, ..., 2, 8, 0])]]

In [ ]:
len(all_model_results_pickle_file[0])

11

In [ ]:
str_config = all_model_results_pickle_file[0][0]
train_loss = all_model_results_pickle_file[0][1]
dev_loss = all_model_results_pickle_file[0][2]
train_mcc = all_model_results_pickle_file[0][3]
train_f1_score = all_model_results_pickle_file[0][4]
dev_mcc = all_model_results_pickle_file[0][5]
dev_f1_score = all_model_results_pickle_file[0][6]
all_dev_label_ids = all_model_results_pickle_file[0][7]
dev_preds = all_model_results_pickle_file[0][8]
train_label_ids = all_model_results_pickle_file[0][9]
train_preds = all_model_results_pickle_file[0][10]

In [ ]:
str_config

'<__main__.obj object at 0x7f098018dac8>'

In [ ]:
%autoreload
train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds )


 label: [8 8 8 ... 2 8 0]

 preds: [8 8 8 ... 2 8 0]

 label: [6 8 8 ... 5 8 1]

 preds: [6 8 8 ... 5 8 1]


In [ ]:
dev_df_results[(dev_df_results['matched'] == False) & (dev_df_results['labels']=='ADE-Drug')]

labels    predicted  matched
985    ADE-Drug  Reason-Drug  False  
986    ADE-Drug  Reason-Drug  False  
2184   ADE-Drug  Reason-Drug  False  
2554   ADE-Drug  Reason-Drug  False  
4251   ADE-Drug  Reason-Drug  False  
4299   ADE-Drug  Reason-Drug  False  
4783   ADE-Drug  Reason-Drug  False  
5196   ADE-Drug  Reason-Drug  False  
5380   ADE-Drug  no relation  False  
6326   ADE-Drug  Reason-Drug  False  
8250   ADE-Drug  Reason-Drug  False  
8351   ADE-Drug  Reason-Drug  False  
8629   ADE-Drug  Reason-Drug  False  
9091   ADE-Drug  Reason-Drug  False  
9209   ADE-Drug  no relation  False  
9906   ADE-Drug  Reason-Drug  False  
10597  ADE-Drug  Reason-Drug  False  
13199  ADE-Drug  Reason-Drug  False  
14394  ADE-Drug  Reason-Drug  False  
14953  ADE-Drug  Reason-Drug  False

In [ ]:
dev_df[dev_df['relation_code'] == 7].iloc[0:20, :]

id  relation_code  ... dev_preds dev_true_ids
10    56    7              ...  0         0          
79    407   7              ...  8         8          
109   575   7              ...  8         8          
110   576   7              ...  6         6          
217   1143  7              ...  8         8          
495   2584  7              ...  8         8          
499   2607  7              ...  2         2          
558   2904  7              ...  1         1          
612   3192  7              ...  6         6          
796   4187  7              ...  8         8          
858   4464  7              ...  1         1          
859   4467  7              ...  3         3          
1009  5255  7              ...  8         8          
1011  5264  7              ...  5         5          
1196  6051  7              ...  2         2          
1496  7574  7              ...  3         3          
1497  7577  7              ...  8         8          
1820  9130  7              ...  3         3          
1883  9433  7              ...  7         7          
1991  9935  7              ...  6         6          

[20 rows x 6 columns]

In [ ]:
print(len(dev_preds))
print(len(dev_preds) == len(all_dev_label_ids))

15304
True


In [ ]:
#import numpy as np
#missed_outputs = np.where((dev_preds) != (all_dev_label_ids))[0]

In [ ]:
#len(missed_outputs)

184

In [ ]:
import pandas as pd
dev_df = pd.read_csv("data_divided/dev.tsv", sep = "\t", header=None)
dev_df = dev_df.rename(columns={0: "id", 1: "relation_code", 2: "alpha", 3:"string"})

In [ ]:
len(dev_df)

15304

In [ ]:
dev_df['dev_preds'] = pd.Series(dev_preds)
dev_df['dev_true_ids'] = pd.Series(all_dev_label_ids)

In [ ]:
pd.set_option('display.max_colwidth', -1)
dev_df[(dev_df['dev_preds'] != dev_df['dev_true_ids']) & (dev_df['relation_code']==7)]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


id  relation_code  ... dev_preds dev_true_ids
2722   13470  7              ...  2         1          
11891  59272  7              ...  1         2          
13814  69030  7              ...  3         2          
14291  71375  7              ...  8         0          
14394  71810  7              ...  7         0          

[5 rows x 6 columns]

In [ ]:
dev_df['dev_preds'].value_counts()

8    8201
2    1382
3    1269
1    1145
0    1034
5     954
6     933
7     250
4     136
Name: dev_preds, dtype: int64

In [ ]:
dev_df['dev_true_ids'].value_counts()

8    8203
2    1378
3    1278
1    1142
0    1032
5    951 
6    935 
7    250 
4    135 
Name: dev_true_ids, dtype: int64

##  Try with different configuration

### Just change model from BIOR to BERT Sequence

In [ ]:
config.programsettings.MODEL_NAME = "BERT_Sequence"
config.programsettings.DEBUG_PRINT = 0

In [ ]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

INFO:root:***** Running training *****
INFO:root:  Num examples = 61014
INFO:root:  Batch size = 12
INFO:root:  Num steps = 50840
INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased.tar.gz from cache at cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c
INFO:pytorch_pretrained_bert.modeling:extracting archive file cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c to temp dir C:\Users\pnarsina\AppData\Local\Temp\2\tmp8umad1wl
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_v

C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Epoch:  10%|███████▎                                                                 | 1/10 [12:02<1:48:22, 722.50s/it]


so far epoch accuracy:  0.9336709607631035


Epoch:  20%|██████████████▌                                                          | 2/10 [24:03<1:36:16, 722.08s/it]


so far epoch accuracy:  0.9750876847936539


Epoch:  30%|█████████████████████▉                                                   | 3/10 [36:05<1:24:13, 721.97s/it]


so far epoch accuracy:  0.9789556495230602


Epoch:  40%|█████████████████████████████▏                                           | 4/10 [48:06<1:12:10, 721.67s/it]


so far epoch accuracy:  0.9814796604058085


Epoch:  50%|███████████████████████████████████▌                                   | 5/10 [1:00:08<1:00:08, 721.68s/it]


so far epoch accuracy:  0.982790834890353


Epoch:  60%|███████████████████████████████████████████▊                             | 6/10 [1:12:09<48:06, 721.65s/it]


so far epoch accuracy:  0.9841839577801816


Epoch:  70%|███████████████████████████████████████████████████                      | 7/10 [1:24:10<36:03, 721.33s/it]


so far epoch accuracy:  0.9849706624709084


Epoch:  80%|██████████████████████████████████████████████████████████▍              | 8/10 [1:36:10<24:01, 720.99s/it]


so far epoch accuracy:  0.9855606909889534


Epoch:  90%|█████████████████████████████████████████████████████████████████▋       | 9/10 [1:48:11<12:01, 721.01s/it]


so far epoch accuracy:  0.986265447274396


Epoch: 100%|████████████████████████████████████████████████████████████████████████| 10/10 [2:00:12<00:00, 721.21s/it]


so far epoch accuracy:  0.9869374241977251
Training complete
Best val Acc: 0.986937


INFO:root:***** Running training *****
INFO:root:  Num examples = 15304
INFO:root:  Batch size = 12
INFO:root:  Num steps = 12750


In [ ]:

train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds)


 label: [5 8 6 ... 1 2 8]

 preds: [5 8 6 ... 1 2 8]

 label: [8 0 8 ... 8 8 8]

 preds: [8 0 8 ... 8 8 8]


In [ ]:
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score, 
                               all_dev_label_ids, dev_preds,train_label_ids,train_preds  ])
all_experiment_results

[['<__main__.obj object at 0x00000145C2150790>',
  0.028281437373610104,
  0.10090719395104036,
  0.9828714870380854,
  0.9811421345806985,
  0.9655254255851637,
  0.9513203962222588],
 ['<__main__.obj object at 0x00000145C2150790>',
  0.029586662868419118,
  0.09663268666182578,
  0.9826565895445114,
  0.9813933562820968,
  0.9658135876808309,
  0.9538088513676909,
  array([8, 0, 8, ..., 8, 8, 8], dtype=int64),
  array([5, 8, 6, ..., 1, 2, 8], dtype=int64)]]

In [ ]:
dev_label_matches_df

predicted
labels         matched           
ADE-Drug       False           31
               True           219
Dosage-Drug    False           25
               True           908
Duration-Drug  False            8
               True           128
Form-Drug      False           60
               True           894
Frequency-Drug False           53
               True          1216
Reason-Drug    False           39
               True           995
Route-Drug     False           42
               True          1103
Strength-Drug  False           60
               True          1322
no relation    False           38
               True          8163

In [ ]:

all_model_results_pickle_file = config.programsettings.REPORTS_DIR + "multi_model_experiment_results_" + str(datetime.now()).replace(":", "_").replace(".", "_") + ".pkl"
with open(all_model_results_pickle_file, "wb") as f:
    pickle.dump(all_experiment_results, f)  


In [ ]:
for i in range(0,50):
    print (all_dev_label_ids[i], dev_preds[i])


8 8
0 0
8 8
0 0
6 6
1 1
2 2
2 2
0 0
8 8
8 8
8 8
2 2
6 6
0 0
8 8
0 0
6 6
6 6
6 6
2 2
8 8
8 8
2 2
8 8
8 8
6 6
0 0
6 6
8 8
8 8
0 0
8 8
0 8
8 8
5 5
8 8
8 8
8 8
8 8
8 8
8 8
8 8
2 2
8 8
8 8
0 0
8 8
0 0
8 8


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(all_dev_label_ids,dev_preds ))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1034
           1       0.97      0.96      0.97      1145
           2       0.94      0.96      0.95      1382
           3       0.94      0.96      0.95      1269
           4       0.97      0.94      0.96       136
           5       0.95      0.94      0.94       954
           6       0.98      0.97      0.97       933
           7       0.91      0.88      0.89       250
           8       1.00      1.00      1.00      8201

    accuracy                           0.98     15304
   macro avg       0.96      0.95      0.95     15304
weighted avg       0.98      0.98      0.98     15304

