In [5]:
import os, json
from types import SimpleNamespace
from experiment import run_model
from eval import calculate_stats
import pickle
from datetime import datetime 
import torch

In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# device = "cpu"

In [7]:
config_folder = "config/"

class obj(object):
    def __init__(self, d):
        for a, b in d.items():
            if isinstance(b, (list, tuple)):
               setattr(self, a, [obj(x) if isinstance(x, dict) else x for x in b])
            else:
               setattr(self, a, obj(b) if isinstance(b, dict) else b)

with open(os.path.join(config_folder, "config.json")) as f:
    config = obj(json.load(f))

In [8]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

100%|████████████████████████████████████████████████████████████████████████████| 61014/61014 [11:52<00:00, 85.68it/s]
INFO:root:***** Running training *****
INFO:root:  Num examples = 61014
INFO:root:  Batch size = 12
INFO:root:  Num steps = 50840
Epoch:   0%|                                                                                    | 0/10 [00:00<?, ?it/s]

C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Epoch:  10%|███████▎                                                                 | 1/10 [10:06<1:30:55, 606.19s/it]


so far epoch accuracy:  0.942193594912643


Epoch:  20%|██████████████▌                                                          | 2/10 [20:12<1:20:49, 606.24s/it]


so far epoch accuracy:  0.9761038450191759


Epoch:  30%|█████████████████████▉                                                   | 3/10 [30:22<1:10:52, 607.47s/it]


so far epoch accuracy:  0.98008653751598


Epoch:  40%|█████████████████████████████▏                                           | 4/10 [40:30<1:00:44, 607.40s/it]


so far epoch accuracy:  0.98203690956174


Epoch:  50%|█████████████████████████████████████▌                                     | 5/10 [50:36<50:35, 607.19s/it]


so far epoch accuracy:  0.9831022388304324


Epoch:  60%|███████████████████████████████████████████▊                             | 6/10 [1:00:42<40:27, 606.78s/it]


so far epoch accuracy:  0.9846428688497721


Epoch:  70%|███████████████████████████████████████████████████                      | 7/10 [1:10:49<30:20, 606.82s/it]


so far epoch accuracy:  0.9856262497131806


Epoch:  80%|██████████████████████████████████████████████████████████▍              | 8/10 [1:20:55<20:13, 606.53s/it]


so far epoch accuracy:  0.9865276821713049


Epoch:  90%|█████████████████████████████████████████████████████████████████▋       | 9/10 [1:31:06<10:07, 607.99s/it]


so far epoch accuracy:  0.9869046448356115


Epoch: 100%|████████████████████████████████████████████████████████████████████████| 10/10 [1:41:14<00:00, 607.43s/it]


so far epoch accuracy:  0.9872979971809749
Training complete
Best val Acc: 0.987298


100%|████████████████████████████████████████████████████████████████████████████| 15304/15304 [02:58<00:00, 85.74it/s]
INFO:root:***** Running training *****
INFO:root:  Num examples = 15304
INFO:root:  Batch size = 12
INFO:root:  Num steps = 12750


In [9]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds

(tensor([0, 1, 1,  ..., 8, 8, 8]),
 array([2, 6, 8, ..., 8, 8, 5], dtype=int64),
 0.028906684944097313,
 tensor([0, 4, 0,  ..., 8, 8, 8]),
 0.10180803557259738,
 array([6, 8, 8, ..., 8, 8, 3], dtype=int64))

In [10]:
import numpy as np
np.array(all_dev_label_ids).shape, np.array(dev_preds).shape, np.array(train_preds).shape, np.array(train_label_ids).shape

((15304,), (15304,), (61014,), (61014,))

In [11]:

train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds )

In [12]:
all_experiment_results = []
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score  ])
all_experiment_results

[['<__main__.obj object at 0x000001D41F750A30>',
  0.028906684944097313,
  0.10180803557259738,
  -0.003843105671395784,
  0.1074325556128981,
  0.0008978060988466196,
  0.11099683082496413]]

In [13]:
dev_label_matches_df

predicted
labels         matched           
ADE-Drug       False          246
               True             4
Dosage-Drug    False          879
               True            54
Duration-Drug  False          135
               True             1
Form-Drug      False          911
               True            43
Frequency-Drug False         1162
               True           107
Reason-Drug    False          964
               True            70
Route-Drug     False         1049
               True            96
Strength-Drug  False         1240
               True           142
no relation    False         3819
               True          4382

##  Try with different configuration

### Just change model from BIOR to BERT Sequence

In [14]:
config.programsettings.MODEL_NAME = "BERT_Sequence"
config.programsettings.DEBUG_PRINT = 0

In [ ]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

INFO:root:***** Running training *****
INFO:root:  Num examples = 61014
INFO:root:  Batch size = 12
INFO:root:  Num steps = 50840
INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased.tar.gz from cache at cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c
INFO:pytorch_pretrained_bert.modeling:extracting archive file cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c to temp dir C:\Users\pnarsina\AppData\Local\Temp\2\tmp9cwpem4g
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_v

C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "


In [ ]:

train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds)

In [ ]:
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score, dev_preds,train_preds  ])
all_experiment_results

In [ ]:
dev_label_matches_df

In [ ]:

all_model_results_pickle_file = config.programsettings.REPORTS_DIR + "multi_model_experiment_results_" + str(datetime.now()).replace(":", "_").replace(".", "_") + ".pkl"
with open(all_model_results_pickle_file, "wb") as f:
    pickle.dump(all_experiment_results, f)  


In [ ]:
for i in range(0,100):
    print (all_dev_label_ids.numpy()[i], dev_preds[i])
