In [1]:
import os, json
from types import SimpleNamespace
from experiment import run_model
from eval import calculate_stats
import pickle
from datetime import datetime 
import torch

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# device = "cpu"

In [3]:
config_folder = "config/"

class obj(object):
    def __init__(self, d):
        for a, b in d.items():
            if isinstance(b, (list, tuple)):
               setattr(self, a, [obj(x) if isinstance(x, dict) else x for x in b])
            else:
               setattr(self, a, obj(b) if isinstance(b, dict) else b)

with open(os.path.join(config_folder, "config.json")) as f:
    config = obj(json.load(f))

In [ ]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

  0%|▏                                                                             | 137/76318 [00:04<42:54, 29.60it/s]

In [5]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds

(tensor([0, 1, 1, 2, 1, 3, 4, 2, 1, 4, 3, 2, 5, 5, 0, 0, 0, 4, 4, 0, 0, 6, 6, 6,
         0, 4, 0, 1, 0, 0, 0, 0, 4, 4, 0, 1, 1, 6, 6, 6, 2, 2, 0, 0, 0, 2, 1, 3,
         0, 6, 0, 4, 0, 5, 5, 0, 7, 7, 7, 6, 0, 0, 0, 0, 2, 2, 1, 3, 2, 6, 5, 4,
         4, 4, 5, 2, 3, 2, 5, 4, 6, 1, 3, 3, 0, 2, 5, 6, 1, 0, 3, 2, 5, 5, 6, 6,
         1, 1, 3, 0]),
 array([3, 3, 2, 3, 2, 3, 2, 4, 3, 6, 6, 4, 6, 6, 6, 4, 2, 3, 4, 4, 4, 4,
        6, 4, 3, 3, 3, 4, 3, 3, 3, 3, 6, 3, 6, 3, 4, 8, 6, 3, 6, 6, 3, 3,
        3, 4, 3, 3, 4, 3, 2, 3, 4, 8, 7, 3, 6, 6, 3, 6, 3, 4, 2, 4, 4, 6,
        4, 3, 4, 4, 4, 3, 6, 3, 3, 3, 3, 6, 3, 4, 6, 3, 4, 4, 4, 4, 3, 3,
        3, 4, 6, 3, 3, 3, 3, 4, 6, 4, 3, 6], dtype=int64),
 2.294666634665595,
 tensor([3, 4, 0, 3, 1, 0, 0, 7, 7, 7, 7, 7, 7, 1, 3, 1, 5, 7, 7, 0, 0, 5, 1, 3,
         3, 2, 1, 3, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
         8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
         8, 8, 8, 8, 8, 8, 8, 8, 8,

In [6]:

train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds )

In [7]:
all_experiment_results = []
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score  ])
all_experiment_results

[['<__main__.obj object at 0x000001E377597550>',
  2.294666634665595,
  2.288866784837511,
  0.004174647419871997,
  0.11,
  -0.04811280200229936,
  0.02]]

##  Try with different configuration

### Just change model from BIOR to BERT Sequence

In [8]:
config.programsettings.MODEL_NAME = "BERT_Sequence"
config.programsettings.DEBUG_PRINT = 0

In [9]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

INFO:root:***** Running training *****
INFO:root:  Num examples = 100
INFO:root:  Batch size = 12
INFO:root:  Num steps = 8
INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased.tar.gz from cache at cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c
INFO:pytorch_pretrained_bert.modeling:extracting archive file cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c to temp dir C:\Users\pnars\AppData\Local\Temp\tmp_cdydwpq
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size":

Epoch: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:42<00:00, 42.59s/it]


so far epoch accuracy:  0.09


INFO:root:***** Running training *****
INFO:root:  Num examples = 100
INFO:root:  Batch size = 12
INFO:root:  Num steps = 8


In [10]:

train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds )

In [11]:
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score  ])
all_experiment_results

[['<__main__.obj object at 0x000001E377597550>',
  2.294666634665595,
  2.288866784837511,
  0.004174647419871997,
  0.11,
  -0.04811280200229936,
  0.02],
 ['<__main__.obj object at 0x000001E377597550>',
  2.23349306318495,
  2.232522620095147,
  -0.031124947496545475,
  0.05000000000000001,
  -0.0589870419701624,
  0.52]]

In [12]:
dev_label_matches_df

predicted
labels         matched           
ADE-Drug       False            8
Duration-Drug  False            1
Form-Drug      False            2
Frequency-Drug False            7
Reason-Drug    False            5
Route-Drug     False            5
Strength-Drug  False            1
no relation    False           19
               True            52

In [18]:

all_model_results_pickle_file = config.programsettings.REPORTS_DIR + "multi_model_experiment_results_" + str(datetime.now()).replace(":", "_").replace(".", "_") + ".pkl"
with open(all_model_results_pickle_file, "wb") as f:
    pickle.dump(all_experiment_results, f)  
