## Setting the environment for Colab

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd "/content/drive/My Drive/Colab Notebooks/w266_final/project_re"

/content/drive/.shortcut-targets-by-id/1I3W7Z7rz_YfsjBjX7z4zTzGbr-iKTrmD/w266_final/project_re


In [3]:
#pip installations for colab
!pip install transformers
!pip install pytorch_pretrained_bert

     |████████████████████████████████| 1.3MB 14.7MB/s 
     |████████████████████████████████| 2.9MB 62.4MB/s 
     |████████████████████████████████| 890kB 63.3MB/s 
     |████████████████████████████████| 1.1MB 57.2MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=30c4a3dba6fd15c42409f207e175269f8e9fbb64c2c36776bcdfd8dbc796bed5
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses
     |████████████████████████████████| 133kB 13.3MB/s 
     |████████████████████████████████| 133kB 17.9MB/s 
     |████████████████████████████████| 71kB 8.4MB/s 
     |████████████████████████████████| 6.8MB 20.0MB/s 
ERROR: botocore 1.19.21 has requirement urllib3<1.27,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.24.3 which is incompatible.


In [5]:
#%load_ext autoreload
%autoreload
import os, json
from types import SimpleNamespace
from experiment import run_model
from eval import calculate_stats
import pickle
from datetime import datetime 
import torch

In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# device = "cpu"

In [7]:
config_folder = "config/"

class obj(object):
    def __init__(self, d):
        for a, b in d.items():
            if isinstance(b, (list, tuple)):
               setattr(self, a, [obj(x) if isinstance(x, dict) else x for x in b])
            else:
               setattr(self, a, obj(b) if isinstance(b, dict) else b)

with open(os.path.join(config_folder, "config.json")) as f:
    config = obj(json.load(f))

In [8]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

INFO:filelock:Lock 140319887786448 acquired on /root/.cache/torch/transformers/6508e60ab3c1200bffa26c95f4b58ac6b6d95fba4db1f195f632fa3cd7bc64cc.437aa611e89f6fc6675a049d2b5545390adbc617e7d655286421c191d2be2791.lock


INFO:filelock:Lock 140319887786448 released on /root/.cache/torch/transformers/6508e60ab3c1200bffa26c95f4b58ac6b6d95fba4db1f195f632fa3cd7bc64cc.437aa611e89f6fc6675a049d2b5545390adbc617e7d655286421c191d2be2791.lock


100%|██████████| 61014/61014 [16:32<00:00, 61.50it/s]
INFO:root:***** Running training *****
INFO:root:  Num examples = 61014
INFO:root:  Batch size = 12
INFO:root:  Num steps = 25420
INFO:filelock:Lock 140319428567728 acquired on /root/.cache/torch/transformers/b21d5a31a72925e995ffe402c1fc581bbcd2edeccfdfc99c644db9c8993b69c3.8a57b13360e7becd2face5c0f1f453e918ee57ca9cac6babc6a3081963efecbf.lock


INFO:filelock:Lock 140319428567728 released on /root/.cache/torch/transformers/b21d5a31a72925e995ffe402c1fc581bbcd2edeccfdfc99c644db9c8993b69c3.8a57b13360e7becd2face5c0f1f453e918ee57ca9cac6babc6a3081963efecbf.lock


INFO:filelock:Lock 140319428569072 acquired on /root/.cache/torch/transformers/bb92901d75bb47e4613bb4674299260f5771cccd3139fbeeaf2b3e29dae0ce57.2961ba715ddc7fc9de233b7f88e7cd685d828debe7fe8a96aed60b6b75358584.lock


INFO:filelock:Lock 140319428569072 released on /root/.cache/torch/transformers/bb92901d75bb47e4613bb4674299260f5771cccd3139fbeeaf2b3e29dae0ce57.2961ba715ddc7fc9de233b7f88e7cd685d828debe7fe8a96aed60b6b75358584.lock


Epoch:   0%|          | 0/5 [00:00<?, ?it/s]

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Epoch:  20%|██        | 1/5 [09:49<39:17, 589.28s/it]


so far epoch accuracy:  0.940587406169076


Epoch:  40%|████      | 2/5 [19:39<29:28, 589.64s/it]


so far epoch accuracy:  0.9768741600288459


Epoch:  60%|██████    | 3/5 [29:28<19:39, 589.51s/it]


so far epoch accuracy:  0.9801520962402072


Epoch:  80%|████████  | 4/5 [39:16<09:48, 588.85s/it]


so far epoch accuracy:  0.9830858491493756


Epoch: 100%|██████████| 5/5 [49:02<00:00, 588.55s/it]


so far epoch accuracy:  0.9848231553413971
Training complete
Best val Acc: 0.984823


100%|██████████| 15304/15304 [03:56<00:00, 64.69it/s]
INFO:root:***** Running training *****
INFO:root:  Num examples = 15304
INFO:root:  Batch size = 12
INFO:root:  Num steps = 6375


In [9]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds

(array([3, 8, 1, ..., 8, 8, 8]),
 array([3, 8, 1, ..., 8, 8, 8]),
 0.03488674676195158,
 array([3, 5, 2, ..., 6, 8, 8]),
 0.08125158199959444,
 array([3, 3, 2, ..., 6, 8, 8]))

In [10]:
import numpy as np
np.array(all_dev_label_ids).shape, np.array(dev_preds).shape, np.array(train_preds).shape, np.array(train_label_ids).shape

((15304,), (15304,), (61014,), (61014,))

In [11]:
%autoreload
train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds )


 label: [3 8 1 ... 8 8 8]

 preds: [3 8 1 ... 8 8 8]

 label: [3 5 2 ... 6 8 8]

 preds: [3 3 2 ... 6 8 8]


In [12]:
all_experiment_results = []
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score, 
                               all_dev_label_ids, dev_preds,train_label_ids,train_preds  ])
all_experiment_results

[['<__main__.obj object at 0x7f9ec5110ba8>',
  0.03488674676195158,
  0.08125158199959444,
  0.9804796843280401,
  0.9782116849841473,
  0.9650391090120177,
  0.9513648514670202,
  array([3, 5, 2, ..., 6, 8, 8]),
  array([3, 3, 2, ..., 6, 8, 8]),
  array([3, 8, 1, ..., 8, 8, 8]),
  array([3, 8, 1, ..., 8, 8, 8])]]

In [13]:
dev_label_matches_df

predicted
labels         matched           
ADE-Drug       False           34
               True           216
Dosage-Drug    False           26
               True           907
Duration-Drug  False            6
               True           130
Form-Drug      False           66
               True           888
Frequency-Drug False           64
               True          1205
Reason-Drug    False           43
               True           991
Route-Drug     False           41
               True          1104
Strength-Drug  False           48
               True          1334
no relation    False           36
               True          8165

In [14]:
all_model_results_pickle_file = config.programsettings.REPORTS_DIR + "multi_model_experiment_results_" + str(datetime.now()).replace(":", "_").replace(".", "_") + ".pkl"
with open(all_model_results_pickle_file, "wb") as f:
    pickle.dump(all_experiment_results, f)

In [15]:
from sklearn.metrics import classification_report
print(classification_report(all_dev_label_ids,dev_preds ))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1034
           1       0.97      0.96      0.97      1145
           2       0.93      0.97      0.95      1382
           3       0.96      0.95      0.95      1269
           4       0.94      0.96      0.95       136
           5       0.96      0.93      0.94       954
           6       0.98      0.97      0.97       933
           7       0.90      0.86      0.88       250
           8       1.00      1.00      1.00      8201

    accuracy                           0.98     15304
   macro avg       0.95      0.95      0.95     15304
weighted avg       0.98      0.98      0.98     15304



##  Try with different configuration

### Just change model from BIOR to BERT Sequence

In [ ]:
config.programsettings.MODEL_NAME = "BERT_Sequence"
config.programsettings.DEBUG_PRINT = 0

In [ ]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

INFO:root:***** Running training *****
INFO:root:  Num examples = 61014
INFO:root:  Batch size = 12
INFO:root:  Num steps = 50840
INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased.tar.gz from cache at cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c
INFO:pytorch_pretrained_bert.modeling:extracting archive file cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c to temp dir C:\Users\pnarsina\AppData\Local\Temp\2\tmp8umad1wl
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_v

C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Epoch:  10%|███████▎                                                                 | 1/10 [12:02<1:48:22, 722.50s/it]


so far epoch accuracy:  0.9336709607631035


Epoch:  20%|██████████████▌                                                          | 2/10 [24:03<1:36:16, 722.08s/it]


so far epoch accuracy:  0.9750876847936539


Epoch:  30%|█████████████████████▉                                                   | 3/10 [36:05<1:24:13, 721.97s/it]


so far epoch accuracy:  0.9789556495230602


Epoch:  40%|█████████████████████████████▏                                           | 4/10 [48:06<1:12:10, 721.67s/it]


so far epoch accuracy:  0.9814796604058085


Epoch:  50%|███████████████████████████████████▌                                   | 5/10 [1:00:08<1:00:08, 721.68s/it]


so far epoch accuracy:  0.982790834890353


Epoch:  60%|███████████████████████████████████████████▊                             | 6/10 [1:12:09<48:06, 721.65s/it]


so far epoch accuracy:  0.9841839577801816


Epoch:  70%|███████████████████████████████████████████████████                      | 7/10 [1:24:10<36:03, 721.33s/it]


so far epoch accuracy:  0.9849706624709084


Epoch:  80%|██████████████████████████████████████████████████████████▍              | 8/10 [1:36:10<24:01, 720.99s/it]


so far epoch accuracy:  0.9855606909889534


Epoch:  90%|█████████████████████████████████████████████████████████████████▋       | 9/10 [1:48:11<12:01, 721.01s/it]


so far epoch accuracy:  0.986265447274396


Epoch: 100%|████████████████████████████████████████████████████████████████████████| 10/10 [2:00:12<00:00, 721.21s/it]


so far epoch accuracy:  0.9869374241977251
Training complete
Best val Acc: 0.986937


INFO:root:***** Running training *****
INFO:root:  Num examples = 15304
INFO:root:  Batch size = 12
INFO:root:  Num steps = 12750


In [ ]:

train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds)


 label: [5 8 6 ... 1 2 8]

 preds: [5 8 6 ... 1 2 8]

 label: [8 0 8 ... 8 8 8]

 preds: [8 0 8 ... 8 8 8]


In [ ]:
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score, 
                               all_dev_label_ids, dev_preds,train_label_ids,train_preds  ])
all_experiment_results

[['<__main__.obj object at 0x00000145C2150790>',
  0.028281437373610104,
  0.10090719395104036,
  0.9828714870380854,
  0.9811421345806985,
  0.9655254255851637,
  0.9513203962222588],
 ['<__main__.obj object at 0x00000145C2150790>',
  0.029586662868419118,
  0.09663268666182578,
  0.9826565895445114,
  0.9813933562820968,
  0.9658135876808309,
  0.9538088513676909,
  array([8, 0, 8, ..., 8, 8, 8], dtype=int64),
  array([5, 8, 6, ..., 1, 2, 8], dtype=int64)]]

In [ ]:
dev_label_matches_df

predicted
labels         matched           
ADE-Drug       False           31
               True           219
Dosage-Drug    False           25
               True           908
Duration-Drug  False            8
               True           128
Form-Drug      False           60
               True           894
Frequency-Drug False           53
               True          1216
Reason-Drug    False           39
               True           995
Route-Drug     False           42
               True          1103
Strength-Drug  False           60
               True          1322
no relation    False           38
               True          8163

In [ ]:

all_model_results_pickle_file = config.programsettings.REPORTS_DIR + "multi_model_experiment_results_" + str(datetime.now()).replace(":", "_").replace(".", "_") + ".pkl"
with open(all_model_results_pickle_file, "wb") as f:
    pickle.dump(all_experiment_results, f)  


In [ ]:
for i in range(0,50):
    print (all_dev_label_ids[i], dev_preds[i])


8 8
0 0
8 8
0 0
6 6
1 1
2 2
2 2
0 0
8 8
8 8
8 8
2 2
6 6
0 0
8 8
0 0
6 6
6 6
6 6
2 2
8 8
8 8
2 2
8 8
8 8
6 6
0 0
6 6
8 8
8 8
0 0
8 8
0 8
8 8
5 5
8 8
8 8
8 8
8 8
8 8
8 8
8 8
2 2
8 8
8 8
0 0
8 8
0 0
8 8


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(all_dev_label_ids,dev_preds ))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1034
           1       0.97      0.96      0.97      1145
           2       0.94      0.96      0.95      1382
           3       0.94      0.96      0.95      1269
           4       0.97      0.94      0.96       136
           5       0.95      0.94      0.94       954
           6       0.98      0.97      0.97       933
           7       0.91      0.88      0.89       250
           8       1.00      1.00      1.00      8201

    accuracy                           0.98     15304
   macro avg       0.96      0.95      0.95     15304
weighted avg       0.98      0.98      0.98     15304

