In [11]:
# %load_ext autoreload
%autoreload
import os, json
from types import SimpleNamespace
from experiment import run_model
from eval import calculate_stats
import pickle
from datetime import datetime 
import torch

In [2]:
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device = "cpu"

In [3]:
config_folder = "config/"

class obj(object):
    def __init__(self, d):
        for a, b in d.items():
            if isinstance(b, (list, tuple)):
               setattr(self, a, [obj(x) if isinstance(x, dict) else x for x in b])
            else:
               setattr(self, a, obj(b) if isinstance(b, dict) else b)

with open(os.path.join(config_folder, "config.json")) as f:
    config = obj(json.load(f))

In [15]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

INFO:root:***** Running training *****
INFO:root:  Num examples = 99
INFO:root:  Batch size = 12
INFO:root:  Num steps = 80
Epoch:   0%|                                                                                    | 0/10 [00:00<?, ?it/s]

Epoch:  10%|███████▌                                                                    | 1/10 [00:31<04:47, 31.97s/it]


so far epoch accuracy:  0.08080808080808081


Epoch:  20%|███████████████▏                                                            | 2/10 [01:05<04:18, 32.34s/it]

Epoch:  30%|██████████████████████▊                                                     | 3/10 [01:37<03:46, 32.35s/it]


so far epoch accuracy:  0.1919191919191919


Epoch:  40%|██████████████████████████████▍                                             | 4/10 [02:10<03:15, 32.52s/it]


so far epoch accuracy:  0.2222222222222222


Epoch:  50%|██████████████████████████████████████                                      | 5/10 [02:43<02:42, 32.57s/it]


so far epoch accuracy:  0.24242424242424243


Epoch:  60%|█████████████████████████████████████████████▌                              | 6/10 [03:15<02:10, 32.59s/it]


so far epoch accuracy:  0.31313131313131315


Epoch:  70%|█████████████████████████████████████████████████████▏                      | 7/10 [03:49<01:38, 32.78s/it]

Epoch:  80%|████████████████████████████████████████████████████████████▊               | 8/10 [04:21<01:05, 32.78s/it]


so far epoch accuracy:  0.3333333333333333


Epoch:  90%|████████████████████████████████████████████████████████████████████▍       | 9/10 [04:54<00:32, 32.82s/it]


so far epoch accuracy:  0.3838383838383838


Epoch: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [05:27<00:00, 32.78s/it]


so far epoch accuracy:  0.46464646464646464
Training complete
Best val Acc: 0.464646


INFO:root:***** Running training *****
INFO:root:  Num examples = 99
INFO:root:  Batch size = 12
INFO:root:  Num steps = 80


In [16]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds

(array([2, 2, 6, 2, 0, 0, 2, 1, 6, 2, 3, 4, 3, 0, 5, 2, 6, 6, 6, 4, 0, 2,
        2, 6, 5, 3, 0, 0, 4, 5, 4, 2, 1, 2, 2, 5, 1, 1, 0, 5, 2, 5, 6, 3,
        0, 5, 7, 3, 0, 6, 1, 1, 1, 0, 7, 4, 1, 1, 3, 6, 2, 5, 6, 4, 0, 3,
        3, 5, 1, 5, 0, 0, 4, 3, 0, 6, 6, 2, 5, 1, 0, 1, 4, 0, 0, 2, 0, 6,
        6, 0, 4, 0, 6, 0, 0, 1, 3, 1, 6], dtype=int64),
 array([2, 2, 2, 2, 0, 0, 0, 2, 6, 2, 2, 2, 2, 0, 6, 2, 1, 3, 6, 2, 0, 6,
        3, 0, 5, 2, 0, 0, 0, 3, 3, 3, 3, 2, 3, 5, 1, 0, 0, 5, 2, 5, 0, 3,
        2, 5, 6, 0, 0, 0, 2, 2, 0, 0, 6, 3, 2, 1, 3, 2, 2, 3, 0, 3, 0, 3,
        2, 5, 6, 3, 0, 0, 0, 3, 0, 1, 6, 0, 5, 1, 0, 0, 0, 0, 0, 2, 0, 3,
        6, 0, 4, 0, 6, 0, 0, 6, 6, 3, 6], dtype=int64),
 1.4916157854927912,
 array([8, 8, 8, 1, 8, 8, 8, 8, 5, 6, 0, 3, 5, 3, 8, 8, 8, 8, 5, 5, 8, 4,
        8, 0, 4, 0, 8, 8, 8, 8, 3, 2, 8, 0, 7, 2, 0, 2, 8, 8, 0, 0, 0, 8,
        3, 8, 8, 6, 8, 0, 8, 2, 4, 8, 8, 2, 0, 8, 1, 2, 0, 1, 8, 5, 7, 0,
        8, 3, 8, 6, 6, 8, 2, 8, 8, 0, 0, 8, 8, 0, 8, 

In [17]:
import numpy as np
np.array(all_dev_label_ids).shape, np.array(dev_preds).shape, np.array(train_preds).shape, np.array(train_label_ids).shape

((99,), (99,), (99,), (99,))

In [18]:
%autoreload
train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds )


 label: [2 2 6 2 0 0 2 1 6 2 3 4 3 0 5 2 6 6 6 4 0 2 2 6 5 3 0 0 4 5 4 2 1 2 2 5 1
 1 0 5 2 5 6 3 0 5 7 3 0 6 1 1 1 0 7 4 1 1 3 6 2 5 6 4 0 3 3 5 1 5 0 0 4 3
 0 6 6 2 5 1 0 1 4 0 0 2 0 6 6 0 4 0 6 0 0 1 3 1 6]

 preds: [2 2 2 2 0 0 0 2 6 2 2 2 2 0 6 2 1 3 6 2 0 6 3 0 5 2 0 0 0 3 3 3 3 2 3 5 1
 0 0 5 2 5 0 3 2 5 6 0 0 0 2 2 0 0 6 3 2 1 3 2 2 3 0 3 0 3 2 5 6 3 0 0 0 3
 0 1 6 0 5 1 0 0 0 0 0 2 0 3 6 0 4 0 6 0 0 6 6 3 6]

 label: [8 8 8 1 8 8 8 8 5 6 0 3 5 3 8 8 8 8 5 5 8 4 8 0 4 0 8 8 8 8 3 2 8 0 7 2 0
 2 8 8 0 0 0 8 3 8 8 6 8 0 8 2 4 8 8 2 0 8 1 2 0 1 8 5 7 0 8 3 8 6 6 8 2 8
 8 0 0 8 8 0 8 8 1 2 3 1 8 3 0 2 8 8 2 6 0 8 5 0 8]

 preds: [0 4 2 0 6 8 3 0 0 2 0 2 5 0 0 2 0 6 2 2 0 0 6 0 0 1 0 0 0 0 3 3 0 0 6 2 0
 3 0 6 0 0 0 2 2 8 3 6 6 3 0 2 3 3 0 0 0 0 5 2 0 0 2 6 0 0 6 3 2 2 1 6 2 0
 3 0 0 0 6 0 6 0 6 0 5 2 0 2 0 6 3 6 2 2 1 3 3 0 0]


In [12]:
all_experiment_results = []
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score  ])
all_experiment_results

[['<__main__.obj object at 0x000001D41F750A30>',
  0.028906684944097313,
  0.10180803557259738,
  -0.003843105671395784,
  0.1074325556128981,
  0.0008978060988466196,
  0.11099683082496413]]

In [13]:
dev_label_matches_df

predicted
labels         matched           
ADE-Drug       False          246
               True             4
Dosage-Drug    False          879
               True            54
Duration-Drug  False          135
               True             1
Form-Drug      False          911
               True            43
Frequency-Drug False         1162
               True           107
Reason-Drug    False          964
               True            70
Route-Drug     False         1049
               True            96
Strength-Drug  False         1240
               True           142
no relation    False         3819
               True          4382

##  Try with different configuration

### Just change model from BIOR to BERT Sequence

In [14]:
config.programsettings.MODEL_NAME = "BERT_Sequence"
config.programsettings.DEBUG_PRINT = 0

In [ ]:
train_label_ids, train_preds, train_loss, all_dev_label_ids, dev_loss, dev_preds = run_model(config, device)

INFO:root:***** Running training *****
INFO:root:  Num examples = 61014
INFO:root:  Batch size = 12
INFO:root:  Num steps = 50840
INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased.tar.gz from cache at cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c
INFO:pytorch_pretrained_bert.modeling:extracting archive file cache/a803ce83ca27fecf74c355673c434e51c265fb8a3e0e57ac62a80e38ba98d384.681017f415dfb33ec8d0e04fe51a619f3f01532ecea04edbfd48c5d160550d9c to temp dir C:\Users\pnarsina\AppData\Local\Temp\2\tmp9cwpem4g
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_v

C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Epoch:  10%|███████▎                                                                 | 1/10 [11:39<1:44:53, 699.25s/it]


so far epoch accuracy:  0.9114137738879602


Epoch:  20%|██████████████▌                                                          | 2/10 [23:17<1:33:12, 699.03s/it]


so far epoch accuracy:  0.973727341265939


In [ ]:

train_mcc, train_f1_score, train_df_results, train_label_matches_df = calculate_stats(train_label_ids,train_preds )
dev_mcc, dev_f1_score, dev_df_results, dev_label_matches_df = calculate_stats(all_dev_label_ids,dev_preds)

In [ ]:
all_experiment_results.append([str(config), train_loss, dev_loss, train_mcc, train_f1_score,dev_mcc,dev_f1_score, dev_preds,train_preds  ])
all_experiment_results

In [ ]:
dev_label_matches_df

In [ ]:

all_model_results_pickle_file = config.programsettings.REPORTS_DIR + "multi_model_experiment_results_" + str(datetime.now()).replace(":", "_").replace(".", "_") + ".pkl"
with open(all_model_results_pickle_file, "wb") as f:
    pickle.dump(all_experiment_results, f)  


In [ ]:
for i in range(0,100):
    print (all_dev_label_ids.numpy()[i], dev_preds[i])
